version: '3.8'
services:
  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - app-network

  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - "/host/Users/Andrey/.cristalix:/host/Users/Andrey/.cristalix"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge